kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: yarncache
        path: /usr/local/share/.cache/yarn
    commands:
      - docker build --progress plain --compress -t paperplanecc/paperplane-api:ci .

  - name: prepare-docker
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop paperplane-api || true
      - docker rm paperplane-api || true
      - docker image rm paperplanecc/paperplane-api:latest || true
      - docker tag paperplanecc/paperplane-api:ci paperplanecc/paperplane-api:latest || true
      - docker image rm paperplanecc/paperplane-api:ci || true

  - name: prisma-sync-db
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - cd /root/project-config/paperplane-api
        - docker run -t --rm --name paperplane-api-prisma --network root_default -e NODE_ENV=production -v ./.env.production:/paperplane-api/.env.production:ro paperplanecc/paperplane-api:latest yarn dbdeploy:prod

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 20m
      script:
        - cd /root/project-config/paperplane-api
        - docker compose up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
