# 本地运行专用 docker compose 文件
services:
  paperplane-api-local:
    image: paperplanecc/paperplane-api-base:latest
    container_name: paperplane-api-local
    working_dir: /paperplane-api
    init: true
    volumes:
      - ./:/paperplane-api
    ports:
      - '6100:6100'
    environment:
      - NODE_ENV=development
      - TZ=Asia/Shanghai
    extra_hosts:
      - host.docker.internal:host-gateway
    command: 'sh -c "yarn && yarn dev"'
